# This file describes the setup of logging when the program
# is run as standalone. If more information is wanted, try level=DEBUG and
# restart the application.

[loggers]
keys=root,load_standalone,import_logger,stdout,stderr

[handlers]
keys=file_handler,error_file_handler, null

[formatters]
keys=timeStampedFormatter

[logger_root]
level=INFO
handlers=file_handler,error_file_handler

[logger_load_standalone]
qualname=load_standalone
propagate=1
handlers=null

[logger_import_logger]
qualname=import_logger
propagate=1
handlers=null

[logger_stdout]
qualname=stdout
propagate=1
handlers=null

[logger_stderr]
qualname=stderr
propagate=1
handlers=null

[handler_file_handler]
class=handlers.RotatingFileHandler
level=DEBUG
formatter=timeStampedFormatter
args=('info.log','a', 10**6, 1)

[handler_error_file_handler]
class=handlers.RotatingFileHandler
level=ERROR
formatter=timeStampedFormatter
args=('errors.log', 'a', 10**6, 1)

[handler_null]
class=NullHandler
args=()

[formatter_timeStampedFormatter]
format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
datefmt=
